---
- name: VPS Setup
  hosts: vps
  become: yes
  gather_facts: yes  # Ensure system facts are gathered

  vars:
    username: "user"
    password: "{{ '$6$.9Xq9o0C$HkrP2VBYQWZdh48LURUM5sRuAFUwBhUXgqCkft3eiRvjBvI1L0sjRirTa0mB.hJMztvDkV6vMh2vJfR3GpImH0' }}"  # Properly escaped password

  pre_tasks:
    - name: Update apt cache if needed
      apt:
        update_cache: yes
        cache_valid_time: 86400
      changed_when: false

  roles:
    - name: user
      tags:
        - user

    - name: hardening
      tags:
        - hardening

    - name: packages
      tags:
        - packages

    - name: docker
      tags:
        - docker

    - name: fail2ban
      tags:
        - fail2ban
